wcl_specs = {}
wcl_specs['Blood Death Knight'] = [1, 1]
wcl_specs['Frost Death Knight'] = [1, 2]
wcl_specs['Unholy Death Knight'] = [1, 3]
wcl_specs['Balance Druid'] = [2, 1]
wcl_specs['Feral Druid'] = [2, 2]
wcl_specs['Guardian Druid'] = [2, 3]
wcl_specs['Restoration Druid'] = [2, 4]
wcl_specs['Beast Mastery Hunter'] = [3, 1]
wcl_specs['Marksmanship Hunter'] = [3, 2]
wcl_specs['Survival Hunter'] = [3, 3]
wcl_specs['Arcane Mage'] = [4, 1]
wcl_specs['Fire Mage'] = [4, 2]
wcl_specs['Frost Mage'] = [4, 3]
wcl_specs['Brewmaster Monk'] = [5, 1]
wcl_specs['Mistweaver Monk'] = [5, 2]
wcl_specs['Windwalker Monk'] = [5, 3]
wcl_specs['Holy Paladin'] = [6, 1]
wcl_specs['Protection Paladin'] = [6, 2]
wcl_specs['Retribution Paladin'] = [6, 3]
wcl_specs['Discipline Priest'] = [7, 1]
wcl_specs['Holy Priest'] = [7, 2]
wcl_specs['Shadow Priest'] = [7, 3]
wcl_specs['Assassination Rogue'] = [8, 1]
wcl_specs['Subtlety Rogue'] = [8, 3]
wcl_specs['Outlaw Rogue'] = [8, 4]
wcl_specs['Elemental Shaman'] = [9, 1]
wcl_specs['Enhancement Shaman'] = [9, 2]
wcl_specs['Restoration Shaman'] = [9, 3]
wcl_specs['Affliction Warlock'] = [10, 1]
wcl_specs['Demonology Warlock'] = [10, 2]
wcl_specs['Destruction Warlock'] = [10, 3]
wcl_specs['Arms Warrior'] = [11, 1]
wcl_specs['Fury Warrior'] = [11, 2]
wcl_specs['Protection Warrior'] = [11, 3]
wcl_specs['Havoc Demon Hunter'] = [12, 1]
wcl_specs['Vengeance Demon Hunter'] = [12, 2]




