dungeon_encounters = {}
dungeon_encounters["De Other Side"] = 12291
dungeon_encounters["Halls of Atonement"] = 12287
dungeon_encounters["Mists of Tirna Scithe"] = 12290
dungeon_encounters["Plaguefall"] = 12289
dungeon_encounters["Sanguine Depths"] = 12284
dungeon_encounters["Spires of Ascension"] = 12285
dungeon_encounters["The Necrotic Wake"] = 12286
dungeon_encounters["Theater of Pain"] = 12293
dungeon_encounters["Tazavesh: Streets of Wonder"] = 12441
dungeon_encounters["Tazavesh: So'leah's Gambit"] = 12442

sepulcher_encounters = {}
sepulcher_encounters["Vigilant Guardian"] = 2512
sepulcher_encounters["Skolex, the Insatiable Ravener"] = 2542
sepulcher_encounters["Artificer Xy'mox"] = 2553
sepulcher_encounters["Dausegne, the Fallen Oracle"] = 2540
sepulcher_encounters["Prototype Pantheon"] = 2544
sepulcher_encounters["Lihuvim, Principal Architect"] = 2539
sepulcher_encounters["Halondrus the Reclaimer"] = 2529
sepulcher_encounters["Anduin Wrynn"] = 2546
sepulcher_encounters["Lords of Dread"] = 2543
sepulcher_encounters["Rygelon"] = 2549
sepulcher_encounters["The Jailer"] = 2537
