dungeon_encounters = {}
dungeon_encounters["De Other Side"] = 12291
dungeon_encounters["Halls of Atonement"] = 12287
dungeon_encounters["Mists of Tirna Scithe"] = 12290
dungeon_encounters["Plaguefall"] = 12289
dungeon_encounters["Sanguine Depths"] = 12284
dungeon_encounters["Spires of Ascension"] = 12285
dungeon_encounters["The Necrotic Wake"] = 12286
dungeon_encounters["Theater of Pain"] = 12293

sanctum_of_domination_encounters = {}
sanctum_of_domination_encounters["Tarragrue"] = 2423
sanctum_of_domination_encounters["Eye of the Jailer"] = 2433
sanctum_of_domination_encounters["The Nine"] = 2429
sanctum_of_domination_encounters["Soulrender Dormazain"] = 2434
sanctum_of_domination_encounters["Remnant of Ner'zhul"] = 2432
sanctum_of_domination_encounters["Painsmith Raznal"] = 2430
sanctum_of_domination_encounters["Guardian of the First Ones"] = 2436
sanctum_of_domination_encounters["Fatescribe Roh-Kalo"] = 2431
sanctum_of_domination_encounters["Kel'Thuzad"] = 2422
sanctum_of_domination_encounters["Sylvanas Windrunner"] = 2435
