# source: https://wowpedia.fandom.com/wiki/SpecializationID

blizz_spec_ids = {}
blizz_spec_ids['Blood Death Knight'] = 250
blizz_spec_ids['Frost Death Knight'] = 251
blizz_spec_ids['Unholy Death Knight'] = 252
blizz_spec_ids['Balance Druid'] = 102
blizz_spec_ids['Feral Druid'] = 103
blizz_spec_ids['Guardian Druid'] = 104
blizz_spec_ids['Restoration Druid'] = 105
blizz_spec_ids['Beast Mastery Hunter'] = 253
blizz_spec_ids['Marksmanship Hunter'] = 254
blizz_spec_ids['Survival Hunter'] = 255
blizz_spec_ids['Arcane Mage'] = 62
blizz_spec_ids['Fire Mage'] = 63
blizz_spec_ids['Frost Mage'] = 64
blizz_spec_ids['Brewmaster Monk'] = 268
blizz_spec_ids['Mistweaver Monk'] = 270
blizz_spec_ids['Windwalker Monk'] = 269
blizz_spec_ids['Holy Paladin'] = 65
blizz_spec_ids['Protection Paladin'] = 66
blizz_spec_ids['Retribution Paladin'] = 70
blizz_spec_ids['Discipline Priest'] = 256
blizz_spec_ids['Holy Priest'] = 257
blizz_spec_ids['Shadow Priest'] = 258
blizz_spec_ids['Assassination Rogue'] = 259
blizz_spec_ids['Subtlety Rogue'] = 261
blizz_spec_ids['Outlaw Rogue'] = 260
blizz_spec_ids['Elemental Shaman'] = 262
blizz_spec_ids['Enhancement Shaman'] = 263
blizz_spec_ids['Restoration Shaman'] = 264
blizz_spec_ids['Affliction Warlock'] = 265
blizz_spec_ids['Demonology Warlock'] = 266
blizz_spec_ids['Destruction Warlock'] = 267
blizz_spec_ids['Arms Warrior'] = 71
blizz_spec_ids['Fury Warrior'] = 72
blizz_spec_ids['Protection Warrior'] = 73
blizz_spec_ids['Havoc Demon Hunter'] = 577
blizz_spec_ids['Vengeance Demon Hunter'] = 581
blizz_spec_ids['Devastation Evoker'] = 1467
blizz_spec_ids['Preservation Evoker'] = 1468
blizz_spec_ids['Augmentation Evoker'] = 1473
