dungeon_encounters = {}
dungeon_encounters["Brackenhide Hollow"] = 12520
dungeon_encounters["Freehold"] = 61754
dungeon_encounters["Halls of Infusion"] = 12527
dungeon_encounters["Neltharion's Lair"] = 61458
dungeon_encounters["Neltharus"] = 12519
dungeon_encounters["The Underrot"] = 61841
dungeon_encounters["The Vortex Pinnacle"] = 10657
dungeon_encounters["Uldaman: Legacy of Tyr"] = 12451

aberrus_encounters = {}
aberrus_encounters["Kazzara, the Hellforged"] = 2688
aberrus_encounters["The Amalgamation Chamber"] = 2687
aberrus_encounters["The Forgotten Experiments"] = 2693
aberrus_encounters["Assault of the Zaqali"] = 2682
aberrus_encounters["Rashok, the Elder"] = 2680
aberrus_encounters["The Vigilant Steward, Zskarn"] = 2689
aberrus_encounters["Magmorax"] = 2683
aberrus_encounters["Echo of Neltharion"] = 2684
aberrus_encounters["Scalecommander Sarkareth"] = 2685

# vault_encounters = {}
# vault_encounters["Eranog"] = 2587
# vault_encounters["Terros"] = 2639
# vault_encounters["The Primal Council"] = 2590
# vault_encounters["Sennarth, The Cold Breath"] = 2592
# vault_encounters["Dathea, Ascended"] = 2635
# vault_encounters["Kurog Grimtotem"] = 2605
# vault_encounters["Broodkeeper Diurna"] = 2614
# vault_encounters["Raszageth the Storm-Eater"] = 2607

# dungeon_encounters["Algeth'ar Academy"] = 12526
# dungeon_encounters["Court of Stars"] = 61571
# dungeon_encounters["Halls of Valor"] = 61477
# dungeon_encounters["Ruby Life Pools"] = 12521
# dungeon_encounters["Shadowmoon Burial Grounds"] = 61176
# dungeon_encounters["Temple of the Jade Serpent"] = 10960
# dungeon_encounters["The Azure Vault"] = 12515
# dungeon_encounters["The Nokhud Offensive"] = 12516
